baseURL: https://hsong.me/
languageCode: en-us
defaultContentLanguage: en
title: Hans Song

theme: ficurinia
copyright: Hans Song - [GitHub](https://github.com/hans-m-song) - [LinkedIn](https://www.linkedin.com/in/hans-song/)

paginate: 5

security:
  gotemplates:
    allowActionJSTmpl: true

params:
  author: Hans Song
  description: Hans's blog

  articleSummary: false
  paperCards: true
  buttonTags: true
  tagsInArticleTitle: true
  gridView: false
  bigArticleTitle: false
  navtype: standard
  enableShadow: true
  menuStyle: standard
  inputStyle: standard
  enableSearch: true
  searchbarEverywhere: true
  searchMenuLink: false
  mobileHamburgerNav: true
  enableFeatured: false
  underlineTitleLinks: false
  enableSidebarLayout: false
  tocInSidebar: true

menu:
  icons:
    - identifier: github
      name: GitHub
      url: https://github.com/hans-m-song
      weight: 10
    - identifier: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/hans-song/
      weight: 10
