name: Setup Hugo
description: Setup Hugo

inputs:
  tag:
    description: Target release tag
    required: false
    default: latest

outputs:
  tag:
    description: Latest release tag
    value: ${{ steps.get-release.outputs.tag }}
  download-url:
    description: Latest release asset download url
    value: ${{ steps.get-release.outputs.download-url }}

runs:
  using: composite
  steps:
    - id: get-release
      shell: bash
      run: |
        release=$(
          curl https://api.github.com/repos/gohugoio/hugo/releases/${{ inputs.tag }} | \
          jq '{
            id: .id,
            tag: .tag_name,
            created_at: .created_at,
            name: .name,
            assets: [ .assets[] | select(.name | endswith("linux-amd64.deb") and (contains("extended") | not))]
          }'
        )

        echo "tag=$( echo $release | jq '.tag' )" >> $GITHUB_OUTPUT
        echo "download-url=$( echo $release | jq '.assets[0].browser_download_url' )" >> $GITHUB_OUTPUT

    - shell: bash
      run: |
        wget -O ${{ runner.temp }}/hugo.deb ${{ steps.get-release.outputs.download-url }} \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb
