name: Deploy

on:
  push:
    branches:
      - master

env:
  HUGO_VERSION: 0.111.3
  HUGO_ENVIRONMENT: production
  HUGO_ENV: production
  HUGO_BASE_URL: ${{ secrets.SUBDOMAIN_NAME }}.${{ secrets.HOSTED_ZONE_NAME }}
  SUBDOMAIN_NAME: ${{ secrets.SUBDOMAIN_NAME }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment: public

    steps:
      - uses: actions/checkout@v3

      - uses: axatol/actions/setup-hugo@release

      - run: make build

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - run: npm install

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_CDK_DEPLOY_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}@${{ github.repository_owner }}@${{ github.event.repository.name }}@${{ github.job }}@${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - run: npm run diff:ci

  invalidate:
    needs: deploy

    uses: ./.github/workflows/invalidate.yaml
    secrets:
      AWS_CDK_DIFF_ROLE_ARN: ${{ secrets.AWS_CDK_DIFF_ROLE_ARN }}
      AWS_CLOUDFRONT_INVALIDATOR_ROLE_ARN: ${{ secrets.AWS_CLOUDFRONT_INVALIDATOR_ROLE_ARN }}
