name: Deploy

on:
  push:
    branches:
      - master

env:
  HUGO_VERSION: 0.111.3
  HUGO_ENVIRONMENT: production
  HUGO_ENV: production
  HUGO_BASE_URL: ${{ secrets.SUBDOMAIN_NAME }}.${{ secrets.HOSTED_ZONE_NAME }}
  SUBDOMAIN_NAME: ${{ secrets.SUBDOMAIN_NAME }}
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment: public

    steps:
      - run: |
          whoami
          id
          groups
          ls -la ${{ runner.temp }}
          ls -la ${{ runner.tool_cache }}
          ls -la /opt/hostedtoolcache

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - uses: axatol/actions/setup-hugo@release

      - run: make build

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_CDK_DIFF_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}@${{ github.event.repository.owner }}@${{ github.event.repository.name }}@${{ github.job }}@${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - run: npm install

      - run: npm run diff:ci

      - uses: ./.github/actions/invalidate-cloudfront
        with:
          mode: content
