name: Invalidate

on:
  workflow_dispatch:
    inputs:
      mode:
        description: What to invalidate - "content" or "all"
        default: content
        type: choice
        options:
          - pages
          - posts
          - content
          - all

permissions:
  id-token: write
  contents: read

jobs:
  invalidate:
    runs-on: self-hosted
    environment: public

    steps:
      - uses: ./.github/actions/invalidate-cloudfront
        with:
          mode: ${{ inputs.mode }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          lookup-diff-role-arn: ${{ secrets.AWS_CDK_DIFF_ROLE_ARN }}
          invalidator-role-arn: ${{ secrets.AWS_CLOUDFRONT_INVALIDATOR_ROLE_ARN }}
