name: Invalidate

on:
  workflow_dispatch:
    inputs:
      mode:
        description: What to invalidate - "content" or "all"
        default: content
        type: choice
        options:
          - pages
          - posts
          - content
          - all

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment: public

    steps:
      - uses: ./.github/actions/invalidate-cloudfront
        with:
          mode: ${{ inputs.mode }}
