name: Invalidate

on:
  workflow_call:
    secrets:
      AWS_CDK_DIFF_ROLE_ARN:
        required: true
      AWS_CLOUDFRONT_INVALIDATOR_ROLE_ARN:
        required: true
      HOSTED_ZONE_NAME:
        required: true
    inputs:
      mode:
        description: What to invalidate
        default: content
        type: string

  workflow_dispatch:
    inputs:
      mode:
        description: What to invalidate
        default: content
        type: choice
        options:
          - pages
          - posts
          - content
          - all

permissions:
  id-token: write
  contents: read

jobs:
  invalidate:
    runs-on: self-hosted

    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_CLOUDFRONT_INVALIDATOR_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}@${{ github.repository_owner }}@${{ github.event.repository.name }}@${{ github.job }}@${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - id: ssm
        run: |
          distribution_id=$(
            aws ssm get-parameter \
              --region us-east-1 \
              --name /infrastructure/cloudfront/${{ secrets.HOSTED_ZONE_NAME }}/distribution_id \
              --query 'Parameter.Value' \
              --output text
          )

          echo "distribution_id=$distribution_id" >> $GITHUB_OUTPUT

      - id: invalidate
        run: |
          case "${{ inputs.mode }}" in
          posts)
            invalidation=$(
              aws cloudfront create-invalidation \
                --distribution-id ${{ steps.ssm.outputs.distribution_id }} \
                --paths "/categories/*" "/posts/*" "/search/*" "/tags/*" "/index.html" "/index.xml" "/sitemap.xml"
            )
            ;;
          pages)
            invalidation=$(
              aws cloudfront create-invalidation \
                --distribution-id ${{ steps.ssm.outputs.distribution_id }} \
                --paths "/categories/*" "/page/*" "/pages/*" "/search/*" "/index.html" "/index.xml" "/sitemap.xml"
            )
            ;;
          content)
            invalidation=$(
              aws cloudfront create-invalidation \
                --distribution-id ${{ steps.ssm.outputs.distribution_id }} \
                --paths "/categories/*" "/page/*" "/pages/*" "/posts/*" "/search/*" "/tags/*" "/index.html" "/index.xml" "/sitemap.xml"
            )
            ;;
          all)
            invalidation=$(
              aws cloudfront create-invalidation \
                --distribution-id ${{ steps.ssm.outputs.distribution_id }} \
                --paths "/*"
            )
            ;;
          *)
            echo "::error::Invalid mode: ${{ inputs.mode }}"
            exit 1
            ;;
          esac

          invalidation_id=$( echo $invalidation | jq -rM '.Invalidation.Id' )
          echo "invalidation_id=$invalidation_id" >> $GITHUB_OUTPUT

      - run: |
          aws cloudfront wait invalidation-completed \
            --distribution-id ${{ steps.ssm.outputs.distribution_id }} \
            --id ${{ steps.invalidate.outputs.invalidation_id }}
